### ISSUE TITLE
does not follow common pattern for naming

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/ckanext-qgov#111]
Hi @ThrawnCA ,

How would we go about in getting ckan-ex-qgov renamed to ckanext-qgov so it aligns with the rest of the echo system. 

second part how much of this is qld gov specific and more around hardening? i.e. could it be named ckanext-gov-hardening ?

**Comment by ThrawnCA** [comment]
Looks like it's quite feasible to do, and old URLs will be automatically redirected: https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

This extension provides a bunch of functions shared by Open Data and Publications; it's not all about security hardening (though there is some of that).

- PURL integration
- Dropping styling from the sysadmin config
- Blacklisting keywords in account names
- Failed password lockout
- Allowing publishers to create datasets in any group
- Nuanced restricted access to user APIs
- Redirecting to login when attempting to access private datasets
- Custom licence list
- Ensuring new resources get moved to the top of the list
- And a bunch of template helpers for things like organisation stats

**Comment by ThrawnCA** [comment]
This has been renamed, and the old URL automatically redirects.
